gpu: "2"
multi_gpu: null

model_name: PointConv
evaluate: True
resume: True

arch: PointConv

# general args
batch_size: 1
pretrain: experiment/checkpoints/PointConv.pth

dim: 3

num_points: 4096

DEVICE: cuda

dataset: FaceScapeDataSet
data_root: /home/gdut403/HZJ_FILES/Dataset/facescape_vertices_normals

# miscalleneous
workers: 16